name: hci-car-sim-analysis
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - setuptools
  - numpy
  - pandas
  - scipy
  - statsmodels
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyterlab
  - notebook
  - ipykernel
  - tabulate
